name: CI

on: pull_request

env:
  CI: true
  GIT_COMMIT_SHA: ${{ github.sha }}
  GIT_BRANCH: ${{ github.head_ref }}
  CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}

jobs:
  precommit:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Cache pre-commit
        uses: actions/cache@v2
        with:
          path: ~/.cache/pre-commit
          key: pre-commit|${{ env.PY }}|${{ hashFiles('.pre-commit-config.yaml') }}
      - uses: pre-commit/action@v1.0.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Run pre-commit checks
        run: |
          pre-commit run --all-files