name: Kotlin Linter
on: [pull_request]
jobs:
  ktlint:
    name: Run Kotlin Linter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: ktlint
        uses: ScaCap/action-ktlint@master
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review
          level: warning
